import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        alignItems: 'center',
        fontSize: 20,
        textAlign: 'center'
    },
    headline: {
        alignSelf: 'center',
        color: '#191919',
        fontSize: 52,
        fontWeight: "bold",
        letterSpacing: 1.2,
        position: 'absolute',
        marginTop: 30,
        fontFamily: "Cochin",
    },
    header2: {
        width: 360,
        lineHeight: 74,
        letterSpacing: 1,
        alignSelf: 'center',
        textAlign: 'center',
        color: '#191919',
        fontSize: 24,
        fontFamily: 'Helvetica',
    },
    header3: {
        width: '100%',
        lineHeight: 30,
        letterSpacing: 1,
        textAlign: 'center',
        color: '#191919',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Helvetica',
        marginBottom: 20,
    },

    container: {
        flex: 1,
    },
    items: {
        alignSelf: 'center',
        width: 360,
        fontSize: 18,
        marginTop: 10,
        marginBottom: 10,
        lineHeight: 20,
        letterSpacing: 1,
        textAlign: 'center',
        fontFamily: 'Helvetica',
        fontWeight: 'normal',
    },

    left: {
        padding: 1,
        fontSize: 18,
        marginTop: 10,
        lineHeight: 20,
        letterSpacing: 1,
        textAlign: 'left',
        fontFamily: 'Helvetica',
        fontWeight: 'normal',
    },
    info: {
        alignSelf: 'center',
        width: 360,
        lineHeight: 74,
        letterSpacing: 1.2,
        textAlign: 'center',
        marginTop: 10,
        color: '#59724A',
        fontSize: 32,
        fontFamily: 'Helvetica',
        fontWeight: 'bold',
    },
    base: {
        alignSelf: 'center',
        flex: 1,
        backgroundColor: '#fff',
        padding: 12,
    },
    base2: {
        alignSelf: 'center',
        flex: 1,
        backgroundColor: '#EBEBEB',
        padding: 12,
    },
    img: {
        alignSelf: 'center',
        width: 360,
        height: 240,
        borderRadius: 20,
    },
    appButtonContainer: {
        elevation: 8,
        backgroundColor: "#ffa500",
        borderRadius: 10,
        paddingVertical: 5,
        paddingHorizontal: 12,
        marginTop: 30,
        width: "75%",
        alignSelf: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowOpacity: 0.26,
        shadowRadius: 3.68,
    },
    appButtonContainer2: {
        elevation: 8,
        backgroundColor: "#ffa500",
        borderRadius: 10,
        paddingVertical: 5,
        marginTop: 30,
        width: "75%",
        alignSelf: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowOpacity: 0.26,
        shadowRadius: 3.68,
    },
    appButtonContainer3: {
        elevation: 8,
        backgroundColor: "#E5475E",
        borderRadius: 10,
        paddingVertical: 5,
        marginTop: 20,
        width: "75%",
        alignSelf: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowOpacity: 0.26,
        shadowRadius: 3.68,
    },
    appButtonText: {
        fontFamily: 'Helvetica',
        fontSize: 20,
        padding: 6,
        color: "#fff",
        fontWeight: "bold",
        alignSelf: "center",
        textTransform: "uppercase"
    },
    color: {
        color: 'red',
        alignSelf: 'center',
        fontFamily: 'Helvetica',
        fontSize: 18,
        letterSpacing: 1.2,
        marginTop: 10,
    },
    input: {
        fontSize: 20,
        marginBottom: 28,
        borderWidth: 1,
        padding: 10,
        borderColor: "#ccc",
        borderRadius: 3,
    },
    form: {
        lineHeight: 74,
        letterSpacing: 1,
        textAlign: 'left',
        color: '#191919',
        fontSize: 20,
        fontFamily: 'Helvetica',
    },
    deliveryContainer: {
        alignSelf: 'center',
        width: 360,
        borderWidth: 1,
        backgroundColor: '#fff',
        margin: 10,
        justifyContent: "space-between",
        borderRadius: 20,
        padding: 10,
    },
});
